name: build-macos-apps
on:
  workflow_dispatch:

env:
  ODS_FILE: platove-tabulky-2025.ods

jobs:
  build:
    # Stavíme dvě varianty: Apple Silicon (macos-14) a Intel (macos-13)
    strategy:
      matrix:
        runner: [macos-14, macos-13]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip tooling
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install runtime deps
        run: pip install pandas odfpy

      - name: Install PyInstaller explicitly
        run: python -m pip install pyinstaller

      - name: Show PyInstaller version (sanity check)
        run: python -m PyInstaller --version

      - name: Build console binary (CLI)
        run: >
          python -m PyInstaller --onefile
          --name OsobniPriplatek
          --add-data "${{ env.ODS_FILE }}:."
          --hidden-import odf
          osobni_priplatek_vypocet.py

      - name: Build GUI app (.app bundle)
        run: >
          python -m PyInstaller --onefile --windowed
          --name OsobniPriplatekGUI
          --add-data "${{ env.ODS_FILE }}:."
          --hidden-import odf
          osobni_priplatek_gui.py

      - name: Zip .app for download
        run: |
          ditto -c -k --sequesterRsrc --keepParent "dist/OsobniPriplatekGUI.app" "dist/OsobniPriplatekGUI-${{ matrix.runner }}.app.zip"

      - name: Rename CLI for arch clarity
        run: |
          cp "dist/OsobniPriplatek" "dist/OsobniPriplatek-${{ matrix.runner }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OsobniPriplatek-${{ matrix.runner }}
          path: |
            dist/OsobniPriplatek-${{ matrix.runner }}
            dist/OsobniPriplatekGUI-${{ matrix.runner }}.app.zip

