name: build-windows-exe
on:
  workflow_dispatch:

env:
  ODS_FILE: platove-tabulky-2025.ods

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip tooling
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install runtime deps
        run: pip install pandas odfpy

      - name: Install PyInstaller explicitly
        run: python -m pip install pyinstaller

      - name: Show PyInstaller version (sanity check)
        run: python -m PyInstaller --version

      - name: Build console exe
        run: >
          python -m PyInstaller --onefile
          --name OsobniPriplatek
          --add-data "${{ env.ODS_FILE }};."
          --hidden-import odf
          osobni_priplatek_vypocet.py

      - name: Build GUI exe
        run: >
          python -m PyInstaller --onefile --windowed
          --name OsobniPriplatekGUI
          --add-data "${{ env.ODS_FILE }};."
          --hidden-import odf
          osobni_priplatek_gui.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OsobniPriplatek-windows
          path: |
            dist/OsobniPriplatek.exe
            dist/OsobniPriplatekGUI.exe

